// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sev1.Congratulations.DataAccess;

namespace Congratulations.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211122231302_CongratulationSeedsWereAdded")]
    partial class CongratulationSeedsWereAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CongratulationTag", b =>
                {
                    b.Property<int>("CongratulationsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("CongratulationsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TagCongratulation");
                });

            modelBuilder.Entity("Sev1.Congratulations.Domain.Congratulation", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RegionId");

                    b.ToTable("Congratulations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "299411 г. Москва, ул. Тургенева, 1",
                            Body = "Совокупность всех видов путей сообщения, транспортных средств, технических устройств и сооружений на путях сообщения, обеспечивающих процесс перемещения людей и грузов различного назначения из одного места в другое",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9406),
                            IsDeleted = false,
                            OwnerId = "64dbb199-0a95-4f1a-afcf-10cc827fd3c8",
                            Price = 100m,
                            RegionId = 1,
                            Status = 0,
                            Title = "Продам транспорт"
                        },
                        new
                        {
                            Id = 2,
                            Address = "299812 г. Судак, ул. Сергеева, 2",
                            Body = "Основное назначение автомобиля заключается в совершении транспортной работы. Автомобильный транспорт в промышленно развитых странах занимает ведущее место по сравнению с другими видами транспорта по объёму перевозок пассажиров. Современный автомобиль состоит из 15—20 тысяч деталей, из которых 150—300 являются наиболее важными и требующими наибольших затрат в эксплуатации",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9707),
                            IsDeleted = false,
                            OwnerId = "54b1ff98-6b5f-4c5e-97a9-747095e1f5dc",
                            Price = 400m,
                            RegionId = 2,
                            Status = 0,
                            Title = "Продам автомобиль"
                        },
                        new
                        {
                            Id = 3,
                            Address = "293713 г. Керчь, ул. Куприна, 3",
                            Body = "Классические мотоциклы включают в себя двухколёсные, двухколёсные с боковой коляской, и трёхколёсные; в начале XXI века стали набирать популярность квадроциклы. Мотоциклы также подазделяются по своей конструкции и размерам: мопеды, мокики (имеют небольшой размер двигателя, как правило до 50 см³)",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9710),
                            IsDeleted = false,
                            OwnerId = "c191e5f8-bf5b-40a9-9ab6-4d08704e373b",
                            Price = 900m,
                            RegionId = 3,
                            Status = 0,
                            Title = "Продам мотоцикл"
                        },
                        new
                        {
                            Id = 4,
                            Address = "295314 г. Симферополь, ул. Чернышевского, 4",
                            Body = "Классические мотоциклы включают в себя двухколёсные, двухколёсные с боковой коляской, и трёхколёсные; в начале XXI века стали набирать популярность квадроциклы. Мотоциклы также подазделяются по своей конструкции и размерам: мопеды, мокики (имеют небольшой размер двигателя, как правило до 50 см³)",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9711),
                            IsDeleted = false,
                            OwnerId = "09c529c8-e798-44ac-9eac-e0150182fa4c",
                            Price = 1600m,
                            RegionId = 4,
                            Status = 0,
                            Title = "Продам мототехнику б/у"
                        },
                        new
                        {
                            Id = 5,
                            Address = "292415 г. Ялта, ул. Достоевского, 5",
                            Body = "Грузовой автомобиль (разг. грузовик) — автомобиль, предназначенный для перевозки грузов в кузове или на грузовой платформе. Для обобщённого обозначения машин, созданных на базе грузового автомобиля, используется термин грузовая техника.",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9712),
                            IsDeleted = false,
                            OwnerId = "7e24ccd2-34fd-4289-9a78-1aae93623bae",
                            Price = 2500m,
                            RegionId = 5,
                            Status = 0,
                            Title = "Продам грузовик б/у"
                        },
                        new
                        {
                            Id = 6,
                            Address = "299411 г. Казань, ул. Тургенева, 1",
                            Body = "За считанные месяцы были разработаны, изготовлены и подготовлены к участию во Всесоюзном мотопробеге пять мотоциклов пяти различных моделей. Наиболее удачными были мотоциклы — колоссы «Иж-1» и «Иж-2» с двухцилиндровыми V-образными двигателями рабочим объёмом 1200 см³ и максимальной мощностью 24 л. с. Для своего времени это были чрезвычайно оригинальные и передовые конструкции. Коленчатый вал двигателя располагался продольно, крутящий момент на заднее колесо передавался от трёхступенчатой коробки передач,",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9713),
                            IsDeleted = false,
                            OwnerId = "64dbb199-0a95-4f1a-afcf-10cc827fd3c8",
                            Price = 3600m,
                            RegionId = 6,
                            Status = 0,
                            Title = "Продам спецтехнику"
                        },
                        new
                        {
                            Id = 7,
                            Address = "297812 г. Астрахань, ул. Сергеева, 2",
                            Body = "Недви́жимость — вид имущества, признаваемого в законодательном порядке недвижимым. К недвижимости по происхождению относятся земельные участки, участки недр и все, что прочно связано с землёй, то есть объекты, перемещение которых без несоразмерного ущерба их назначению невозможно, в том числе здания, сооружения, объекты незавершённого строительства.",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9715),
                            IsDeleted = false,
                            OwnerId = "54b1ff98-6b5f-4c5e-97a9-747095e1f5dc",
                            Price = 4900m,
                            RegionId = 7,
                            Status = 0,
                            Title = "Продам недвижимость"
                        },
                        new
                        {
                            Id = 8,
                            Address = "298413 г. Джанкой, ул. Куприна, 3",
                            Body = "Кварти́ра (от нем. Quartier[1]) — один из видов жилого помещения, состоящий из одной или нескольких смежных комнат а также в отдельных случаях с отдельным наружным выходом, составляющее отдельную часть дома.",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9716),
                            IsDeleted = false,
                            OwnerId = "c191e5f8-bf5b-40a9-9ab6-4d08704e373b",
                            Price = 6400m,
                            RegionId = 8,
                            Status = 0,
                            Title = "Продам квартиру"
                        },
                        new
                        {
                            Id = 9,
                            Address = "295314 г. Краснодар, ул. Чернышевского, 4",
                            Body = "Кварти́ра (от нем. Quartier[1]) — один из видов жилого помещения, состоящий из одной или нескольких смежных комнат а также в отдельных случаях с отдельным наружным выходом, составляющее отдельную часть дома.",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9717),
                            IsDeleted = false,
                            OwnerId = "09c529c8-e798-44ac-9eac-e0150182fa4c",
                            Price = 8100m,
                            RegionId = 9,
                            Status = 0,
                            Title = "Продам комнату"
                        },
                        new
                        {
                            Id = 10,
                            Address = "297415 г. Красноярск, ул. Достоевского, 5",
                            Body = "Котте́дж (от англ. cottage) — индивидуальный городской или сельский малоэтажный (обычно двухэтажный) жилой дом с небольшим участком прилегающей земли[1] для постоянного или временного проживания одной нуклеарной семьи. Первый этаж занимают такие помещения как гостиная, кухня, санузел, котельная, часто гараж для легкового автомобиля;",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9718),
                            IsDeleted = false,
                            OwnerId = "7e24ccd2-34fd-4289-9a78-1aae93623bae",
                            Price = 10000m,
                            RegionId = 10,
                            Status = 0,
                            Title = "Продам дом"
                        },
                        new
                        {
                            Id = 11,
                            Address = "299411 г. Москва, ул. Тургенева, 1",
                            Body = "Котте́дж (от англ. cottage) — индивидуальный городской или сельский малоэтажный (обычно двухэтажный) жилой дом с небольшим участком прилегающей земли[1] для постоянного или временного проживания одной нуклеарной семьи. Первый этаж занимают такие помещения как гостиная, кухня, санузел, котельная, часто гараж для легкового автомобиля;",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9720),
                            IsDeleted = false,
                            OwnerId = "64dbb199-0a95-4f1a-afcf-10cc827fd3c8",
                            Price = 12100m,
                            RegionId = 11,
                            Status = 0,
                            Title = "Продам дачу"
                        },
                        new
                        {
                            Id = 12,
                            Address = "299812 г. Судак, ул. Сергеева, 2",
                            Body = "Котте́дж (от англ. cottage) — индивидуальный городской или сельский малоэтажный (обычно двухэтажный) жилой дом с небольшим участком прилегающей земли[1] для постоянного или временного проживания одной нуклеарной семьи. Первый этаж занимают такие помещения как гостиная, кухня, санузел, котельная, часто гараж для легкового автомобиля;",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9721),
                            IsDeleted = false,
                            OwnerId = "54b1ff98-6b5f-4c5e-97a9-747095e1f5dc",
                            Price = 14400m,
                            RegionId = 12,
                            Status = 0,
                            Title = "Продам котедж"
                        },
                        new
                        {
                            Id = 13,
                            Address = "293713 г. Керчь, ул. Куприна, 3",
                            Body = "Возникновению электроники предшествовало открытие и изучение электричества, электромагнетизма, а далее изобретение радио. Поскольку радиопередатчики сразу же нашли применение (в первую очередь на кораблях и в военном деле), для них потребовалась элементная база, созданием и изучением которой и занялась электроника. Элементная база первого поколения была основана на электронных лампах. Соответственно получила развитие вакуумная электроника. Её развитию способствовало также изобретение телевидения и радаров, которые нашли широкое применение во время Второй мировой войны[2][3].Но электронные лампы обладали существенными недостатками. ",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9722),
                            IsDeleted = false,
                            OwnerId = "c191e5f8-bf5b-40a9-9ab6-4d08704e373b",
                            Price = 16900m,
                            RegionId = 13,
                            Status = 0,
                            Title = "Продам электронику"
                        },
                        new
                        {
                            Id = 14,
                            Address = "295314 г. Симферополь, ул. Чернышевского, 4",
                            Body = "Аудиотехника (звуковая техника, звукотехника, аудиоэлектроника) — аппаратура (магнитофоны, ревербераторы, микшеры, усилители, ресиверы и пр.) и устройства (микрофоны, динамики и пр.), предназначенные для записи и воспроизведения аудио (звука).",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9723),
                            IsDeleted = false,
                            OwnerId = "09c529c8-e798-44ac-9eac-e0150182fa4c",
                            Price = 19600m,
                            RegionId = 14,
                            Status = 0,
                            Title = "Продам аудиотехнику б/у"
                        },
                        new
                        {
                            Id = 15,
                            Address = "292415 г. Ялта, ул. Достоевского, 5",
                            Body = "В середине 1980-х годов в СССР начали выпускать первые бытовые VHS- видеомагнитофоны «Электроника ВМ-12», которые стоили 1200 рублей (7-10 средних зарплат того времени[13]), но были дефицитным товаром и продавались по предварительной записи. Существовало даже такое понятие, как очередь на видеомагнитофон.",
                            CategoryId = 10,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9724),
                            IsDeleted = false,
                            OwnerId = "7e24ccd2-34fd-4289-9a78-1aae93623bae",
                            Price = 22500m,
                            RegionId = 15,
                            Status = 0,
                            Title = "Продам видеотехнику б/у"
                        },
                        new
                        {
                            Id = 16,
                            Address = "299411 г. Казань, ул. Тургенева, 1",
                            Body = "Игрова́я приста́вка (игровая консоль) — специализированное электронное устройство, предназначенное для видеоигр; для таких устройств, в отличие от персональных компьютеров, запуск и воспроизв",
                            CategoryId = 11,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9726),
                            IsDeleted = false,
                            OwnerId = "64dbb199-0a95-4f1a-afcf-10cc827fd3c8",
                            Price = 25600m,
                            RegionId = 16,
                            Status = 0,
                            Title = "Продам игру"
                        },
                        new
                        {
                            Id = 17,
                            Address = "297812 г. Астрахань, ул. Сергеева, 2",
                            Body = "Игрова́я приста́вка (игровая консоль) — специализированное электронное устройство, предназначенное для видеоигр; для таких устройств, в отличие от персональных компьютеров, запуск и воспроизв",
                            CategoryId = 11,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9727),
                            IsDeleted = false,
                            OwnerId = "54b1ff98-6b5f-4c5e-97a9-747095e1f5dc",
                            Price = 28900m,
                            RegionId = 17,
                            Status = 0,
                            Title = "Продам приставку"
                        },
                        new
                        {
                            Id = 18,
                            Address = "298413 г. Джанкой, ул. Куприна, 3",
                            Body = "Игрова́я приста́вка (игровая консоль) — специализированное электронное устройство, предназначенное для видеоигр; для таких устройств, в отличие от персональных компьютеров, запуск и воспроизв",
                            CategoryId = 11,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9728),
                            IsDeleted = false,
                            OwnerId = "c191e5f8-bf5b-40a9-9ab6-4d08704e373b",
                            Price = 32400m,
                            RegionId = 18,
                            Status = 0,
                            Title = "Продам программу"
                        },
                        new
                        {
                            Id = 19,
                            Address = "295314 г. Краснодар, ул. Чернышевского, 4",
                            Body = "Насто́льный (стационарный) компью́тер, дескто́п (англ. desktop computer) — стационарный персональный компьютер, предназначенный для работы в офисе и дома. Термин обычно используется для того, чтобы обозначить вид компьютера и отличить его от компьютеров других типов, например портативного компьютера, карманного компьютера, встроенного компьютера или сервера. Как правило, состоит из монитора, системного блока, мыши, клавиатуры и звукогарнитуры",
                            CategoryId = 12,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9729),
                            IsDeleted = false,
                            OwnerId = "09c529c8-e798-44ac-9eac-e0150182fa4c",
                            Price = 36100m,
                            RegionId = 19,
                            Status = 0,
                            Title = "Продам настольный компьютер б/у"
                        },
                        new
                        {
                            Id = 20,
                            Address = "297415 г. Красноярск, ул. Достоевского, 5",
                            Body = "Переносной компьютер, в корпусе которого объединены типичные компоненты ПК, включая дисплей, клавиатуру и устройство указания (обычно сенсорная панель или тачпад), а также аккумуляторные батареи. Ноутбуки отличаются небольшими размерами и весом, время автономной работы ноутбуков варьируется в пределах от 2 до 15 часов.",
                            CategoryId = 13,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9730),
                            IsDeleted = false,
                            OwnerId = "7e24ccd2-34fd-4289-9a78-1aae93623bae",
                            Price = 40000m,
                            RegionId = 20,
                            Status = 0,
                            Title = "Продам ноутбук"
                        },
                        new
                        {
                            Id = 21,
                            Address = "297415 г. Чебоксары, ул. Толстого, 25",
                            Body = "Интернет-планшет (англ. Internet tablet или Web tablet — Веб-планшет, или Pad tablet — Pad-планшет (Блокнотный планшет), или Web-pad — Веб-блокнот, или Surfpad — Веб-сёрфинг-блокнот) — мобильный компьютер, относящийся к типу планшетных компьютеров с диагональю экрана от 7 до 12 дюймов, построенный на аппаратной платформе того же класса, что и платформа для смартфонов.",
                            CategoryId = 14,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9732),
                            IsDeleted = false,
                            OwnerId = "64dbb199-0a95-4f1a-afcf-10cc827fd3c8",
                            Price = 44100m,
                            RegionId = 21,
                            Status = 0,
                            Title = "Продам планшет"
                        },
                        new
                        {
                            Id = 22,
                            Address = "299411 г. Москва, ул. Тургенева, 1",
                            Body = "Электро́нная кни́га (Electronic book; e-book; eBook) — версия книги, хранящаяся в электронном виде, и показываемая на экране, в цифровом формате. Данное понятие применяется как для произведений, представленных в цифровой форме, так и в отношении устройств, используемых для их прочтения.",
                            CategoryId = 14,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9733),
                            IsDeleted = false,
                            OwnerId = "54b1ff98-6b5f-4c5e-97a9-747095e1f5dc",
                            Price = 48400m,
                            RegionId = 22,
                            Status = 0,
                            Title = "Продам электронную книгу"
                        },
                        new
                        {
                            Id = 23,
                            Address = "299812 г. Судак, ул. Сергеева, 2",
                            Body = "С точки зрения экономики и общества возможность осуществления телефонных переговоров рассматривается как благо и важное условие комфортной жизни человека. Существует область науки и техники, связанная с изучением направлений развития телефонной связи, она получила название телефонии.",
                            CategoryId = 15,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9734),
                            IsDeleted = false,
                            OwnerId = "c191e5f8-bf5b-40a9-9ab6-4d08704e373b",
                            Price = 52900m,
                            RegionId = 23,
                            Status = 0,
                            Title = "Продам телефон"
                        },
                        new
                        {
                            Id = 24,
                            Address = "293713 г. Керчь, ул. Куприна, 3",
                            Body = "Комплементарные блага (взаимодополняющие товары) — блага, совместное потребление которых является для агента более предпочтительным, чем потребление каждого",
                            CategoryId = 16,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9735),
                            IsDeleted = false,
                            OwnerId = "09c529c8-e798-44ac-9eac-e0150182fa4c",
                            Price = 57600m,
                            RegionId = 24,
                            Status = 0,
                            Title = "Продам товары для компьютера"
                        },
                        new
                        {
                            Id = 25,
                            Address = "295314 г. Симферополь, ул. Чернышевского, 4",
                            Body = "Фотоаппара́т (фотографи́ческий аппара́т, фотока́мера) — устройство для регистрации неподвижных изображений (получения фотографий). Запись изображения в фотоаппарате осуществляется фотохимическим способом при воздействии света на светочувствительный фотоматериал. Получаемое таким способом скрытое изображение преобразуется в видимое при лабораторной обработке. В цифровом фотоаппарате фотофиксация происходит путём фотоэлектрического преобразования оптического изображения в электрический сигнал, цифровые данные о котором сохраняются на энергонезависимом носителе.",
                            CategoryId = 17,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 6, DateTimeKind.Utc).AddTicks(9736),
                            IsDeleted = false,
                            OwnerId = "7e24ccd2-34fd-4289-9a78-1aae93623bae",
                            Price = 62500m,
                            RegionId = 25,
                            Status = 0,
                            Title = "Продам фотоаппарат б/у"
                        });
                });

            modelBuilder.Entity("Sev1.Congratulations.Domain.Category", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(4691),
                            IsDeleted = false,
                            Name = "Транспорт"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5221),
                            IsDeleted = false,
                            Name = "Автомобили",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5478),
                            IsDeleted = false,
                            Name = "Мотоциклы и мототехника",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5480),
                            IsDeleted = false,
                            Name = "Грузовики и спецтехника",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5481),
                            IsDeleted = false,
                            Name = "Недвижимость"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5482),
                            IsDeleted = false,
                            Name = "Квартиры",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5484),
                            IsDeleted = false,
                            Name = "Комнаты",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5485),
                            IsDeleted = false,
                            Name = "Дома, дачи, коттеджи",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5486),
                            IsDeleted = false,
                            Name = "Электроника"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5487),
                            IsDeleted = false,
                            Name = "Аудио и видео",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5488),
                            IsDeleted = false,
                            Name = "Игры, приставки и программы",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5489),
                            IsDeleted = false,
                            Name = "Настольные компьютеры",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5490),
                            IsDeleted = false,
                            Name = "Ноутбуки",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5491),
                            IsDeleted = false,
                            Name = "Планшеты и электронные книги",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5492),
                            IsDeleted = false,
                            Name = "Телефоны",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5493),
                            IsDeleted = false,
                            Name = "Товары для компьютера",
                            ParentCategoryId = 9
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 19, DateTimeKind.Utc).AddTicks(5494),
                            IsDeleted = false,
                            Name = "Фототехника",
                            ParentCategoryId = 9
                        });
                });

            modelBuilder.Entity("Sev1.Congratulations.Domain.Region", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentRegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentRegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(8894),
                            Name = "Российская Федерация"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9185),
                            Name = "Центральный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9187),
                            Name = "Белгородская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9188),
                            Name = "Брянская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9189),
                            Name = "Владимирская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9190),
                            Name = "Воронежская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9191),
                            Name = "Ивановская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9192),
                            Name = "Калужская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9193),
                            Name = "Костромская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9194),
                            Name = "Курская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9195),
                            Name = "Липецкая область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9196),
                            Name = "Московская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9197),
                            Name = "Орловская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9198),
                            Name = "Рязанская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9199),
                            Name = "Смоленская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9200),
                            Name = "Тамбовская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9201),
                            Name = "Тверская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9202),
                            Name = "Тульская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9203),
                            Name = "Ярославская область",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9203),
                            Name = "г. Москва",
                            ParentRegionId = 2
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9204),
                            Name = "Северо-Западный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9205),
                            Name = "Республика Карелия",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9206),
                            Name = "Республика Коми",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9207),
                            Name = "Архангельская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9208),
                            Name = "в том числе Ненецкий автономный округ",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9209),
                            Name = "Вологодская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9210),
                            Name = "Калининградская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9211),
                            Name = "Ленинградская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9212),
                            Name = "Мурманская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9213),
                            Name = "Новгородская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9214),
                            Name = "Псковская область",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9215),
                            Name = "г. Санкт-Петербург",
                            ParentRegionId = 21
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9216),
                            Name = "Южный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9217),
                            Name = "Республика Адыгея",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9218),
                            Name = "Республика Дагестан",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9219),
                            Name = "Республика Ингушетия",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9219),
                            Name = "Кабардино-Балкарская Республика",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9220),
                            Name = "Республика Калмыкия",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9221),
                            Name = "Карачаево-Черкесская Республика",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9222),
                            Name = "Республика Северная Осетия - Алания",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9223),
                            Name = "Чеченская Республика",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9224),
                            Name = "Краснодарский край",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9225),
                            Name = "Ставропольский край",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9226),
                            Name = "Астраханская область",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9227),
                            Name = "Волгоградская область",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9228),
                            Name = "Ростовская область",
                            ParentRegionId = 33
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9229),
                            Name = "Приволжский федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9230),
                            Name = "Республика Башкортостан",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9231),
                            Name = "Республика Марий Эл",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9232),
                            Name = "Республика Мордовия",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9233),
                            Name = "Республика Татарстан",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9234),
                            Name = "Удмуртская Республика",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9235),
                            Name = "Чувашская Республика",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9236),
                            Name = "Кировская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9237),
                            Name = "Нижегородская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9238),
                            Name = "Оренбургская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9239),
                            Name = "Пензенская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9240),
                            Name = "Пермская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9240),
                            Name = "в том числе Коми-Пермяцкий автономный округ",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9241),
                            Name = "Самарская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9242),
                            Name = "Саратовская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9243),
                            Name = "Ульяновская область",
                            ParentRegionId = 47
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9244),
                            Name = "Уральский федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9245),
                            Name = "Курганская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9246),
                            Name = "Свердловская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9247),
                            Name = "Тюменская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9248),
                            Name = "в том числе Ханты-Мансийский автономный округ - Югра",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9249),
                            Name = "в том числе Ямало-Ненецкий автономный округ",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9250),
                            Name = "в том числе Челябинская область",
                            ParentRegionId = 63
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9251),
                            Name = "Сибирский федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9252),
                            Name = "Республика Алтай",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9253),
                            Name = "Республика Бурятия",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9254),
                            Name = "Республика Тыва",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9255),
                            Name = "Республика Хакасия",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9255),
                            Name = "Алтайский край",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9256),
                            Name = "Красноярский край",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9257),
                            Name = "в том числе Таймырский (Долгано-Ненецкий) автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9258),
                            Name = "Эвенкийский автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9259),
                            Name = "Иркутская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9260),
                            Name = "в том числе Усть-Ордынский Бурятский автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9261),
                            Name = "Кемеровская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9262),
                            Name = "Новосибирская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9263),
                            Name = "Омская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9264),
                            Name = "Томская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9265),
                            Name = "Читинская область",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9266),
                            Name = "в том числе Агинский Бурятский автономный округ",
                            ParentRegionId = 70
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9267),
                            Name = "Дальневосточный федеральный округ",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9268),
                            Name = "Республика Саха (Якутия)",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9269),
                            Name = "Приморский край",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9270),
                            Name = "Хабаровский край",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9271),
                            Name = "Амурская край",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9271),
                            Name = "Камчатская область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9272),
                            Name = "Корякский автономный округ",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9312),
                            Name = "Магаданская область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9313),
                            Name = "Сахалинская область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9314),
                            Name = "Еврейская автономная область",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9315),
                            Name = "Чукотский автономный округ",
                            ParentRegionId = 87
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9316),
                            Name = "Севастополь",
                            ParentRegionId = 1
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2021, 11, 22, 23, 13, 2, 23, DateTimeKind.Utc).AddTicks(9317),
                            Name = "Крым",
                            ParentRegionId = 1
                        });
                });

            modelBuilder.Entity("Sev1.Congratulations.Domain.Tag", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CongratulationTag", b =>
                {
                    b.HasOne("Sev1.Congratulations.Domain.Congratulation", null)
                        .WithMany()
                        .HasForeignKey("CongratulationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sev1.Congratulations.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sev1.Congratulations.Domain.Congratulation", b =>
                {
                    b.HasOne("Sev1.Congratulations.Domain.Category", "Category")
                        .WithMany("Congratulations")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Sev1.Congratulations.Domain.Region", "Region")
                        .WithMany("Congratulations")
                        .HasForeignKey("RegionId");

                    b.Navigation("Category");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Sev1.Congratulations.Domain.Category", b =>
                {
                    b.HasOne("Sev1.Congratulations.Domain.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Sev1.Congratulations.Domain.Region", b =>
                {
                    b.HasOne("Sev1.Congratulations.Domain.Region", "ParentRegion")
                        .WithMany()
                        .HasForeignKey("ParentRegionId");

                    b.Navigation("ParentRegion");
                });

            modelBuilder.Entity("Sev1.Congratulations.Domain.Category", b =>
                {
                    b.Navigation("Congratulations");

                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("Sev1.Congratulations.Domain.Region", b =>
                {
                    b.Navigation("Congratulations");
                });
#pragma warning restore 612, 618
        }
    }
}
